[package]
name = "stem-club-site"
version = "0.1.0"
authors = ["nvarner <nathanmvarner@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.1"
actix-files = "0.2"
askama = "0.9"

[build-dependencies]
askama = "0.9"
